//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quiz
{
    using System;
    using System.Collections.Generic;
    
    public partial class Questionare
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Questionare()
        {
            this.Question = new HashSet<Question>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public int IDUser { get; set; }
        public string URL { get; set; }
        public Nullable<bool> Type { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Question> Question { get; set; }
        public virtual Users Users { get; set; }
    }
}
