//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataClasses.Repositories
{
    using System;
    using System.Collections.Generic;
    
    public partial class NextQuestion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NextQuestion()
        {
            this.NextQuestion1 = new HashSet<NextQuestion>();
        }
    
        public int ID { get; set; }
        public string Answers { get; set; }
        public int IDQuestion { get; set; }
        public Nullable<int> IDNextRule { get; set; }
        public int IDNextQuestion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NextQuestion> NextQuestion1 { get; set; }
        public virtual NextQuestion NextQuestion2 { get; set; }
        public virtual Question Question { get; set; }
        public virtual Question Question1 { get; set; }
    }
}
