//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnsweringQuizes
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;

    public partial class QuizAnswersEntities : DbContext
    {
        public QuizAnswersEntities()
            : base("name=QuizAnswersEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }

        public virtual DbSet<Answers> Answers { get; set; }
        public virtual DbSet<Questions> Questions { get; set; }
        public virtual DbSet<Quizes> Quizes { get; set; }
        public virtual DbSet<Records> Records { get; set; }
        public virtual DbSet<Respondents> Respondents { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
