//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnsweringQuizes
{
    using System;
    using System.Collections.Generic;

    public partial class Records
    {
        public int ID { get; set; }
        public int IDRespondent { get; set; }
        public int IDQuiz { get; set; }
        public int IDQuestion { get; set; }
        public int IDAnswer { get; set; }
        public System.DateTime DateTime { get; set; }

        public virtual Answers Answers { get; set; }
        public virtual Questions Questions { get; set; }
        public virtual Quizes Quizes { get; set; }
        public virtual Respondents Respondents { get; set; }
    }
}
